-- MySQL Script generated by MySQL Workbench
-- Fri Sep 19 19:11:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema yummies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yummies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yummies` DEFAULT CHARACTER SET utf8 ;
USE `yummies` ;

-- -----------------------------------------------------
-- Table `yummies`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yummies`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yummies`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yummies`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `usename` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `id_rol` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `usename_UNIQUE` (`usename` ASC) VISIBLE,
  INDEX `id_rol_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `id_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `yummies`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yummies`.`linea_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yummies`.`linea_productos` (
  `id_linea_productos` INT NOT NULL AUTO_INCREMENT,
  `linea_productos` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id_linea_productos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yummies`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yummies`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  `imagen_url` VARCHAR(100) NULL,
  `precio` DECIMAL NOT NULL,
  `gramaje` DECIMAL NOT NULL,
  `id_linea` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `productos-guia_idx` (`id_linea` ASC) VISIBLE,
  CONSTRAINT `productos-guia`
    FOREIGN KEY (`id_linea`)
    REFERENCES `yummies`.`linea_productos` (`id_linea_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yummies`.`tiendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yummies`.`tiendas` (
  `id_tiendas` INT NOT NULL AUTO_INCREMENT,
  `nombre_tienda` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `nombre_encargado` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id_tiendas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yummies`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yummies`.`pedidos` (
  `id_pedido` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `id_tienda` INT NOT NULL,
  `ubicacion` VARCHAR(150) NOT NULL,
  `id_usuario` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `tienda-pedido_idx` (`id_tienda` ASC) VISIBLE,
  INDEX `usuario-pedido_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `tienda-pedido`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `yummies`.`tiendas` (`id_tiendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario-pedido`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `yummies`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yummies`.`detalle_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yummies`.`detalle_pedidos` (
  `id_detalle_pedidos` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL NOT NULL,
  `subtotal` DECIMAL NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id_detalle_pedidos`),
  INDEX `pedidos-detalle_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `detalle-producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `pedidos-detalle`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `yummies`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `detalle-producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `yummies`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
